#!/usr/bin/env python
database = [
    ['albert',  '1234'],
    ['dilbent', '4242'],
    ['smith',   '7524'],
    ['jone',    '9843']
]

username = raw_input('User name: ')
pin = raw_input('PIN code: ')

if [username,pin] in database: print 'Access granted'
else: print 'Failure granted'
